markdown: kramdown

encoding: "utf-8"

sass:
  sass_dir: css
  style: compressed

widgets:
 -
    name: ggforce
    thumbnail: images/ggforce.png
    url: https://github.com/thomasp85/ggforce
    jslibs: >
       [datamaps](http://datamaps.github.io),[d3](http://d3js.org)
    ghuser: thomasp85
    ghrepo: ggforce
    tags: visualization,general
    cran: true
    release:
    examples:
    ghauthor: thomasp85
    short: >
      ggforce is aimed at providing missing functionality to ggplot2 through the extension system introduced with ggplot2 v2.0.0.
    description: >    
