markdown: kramdown

encoding: "utf-8"

sass:
  sass_dir: css
  style: compressed

widgets:
 -
    name: ggforce
    thumbnail: images/ggforce.png
    url: https://github.com/thomasp85/ggforce
    jslibs: >
    ghuser: thomasp85
    ghrepo: ggforce
    tags: visualization,general
    cran: true
    release:
    examples:
    ghauthor: thomasp85
    short: >
      ggforce is aimed at providing missing functionality to ggplot2 through the extension system introduced with ggplot2 v2.0.0.
    description: >    

 -
    name: rbokeh
    thumbnail: images/bokeh-rbokeh.png
    url: https://hafen.github.io/rbokeh
    jslibs: >
      [bokehjs](http://bokeh.pydata.org/en/latest/)
    ghuser: bokeh
    ghrepo: rbokeh
    tags: visualization,general
    cran: true
    release:
    examples:
    ghauthor: hafen
    short: >
      An interface to Bokeh that provides a flexible, powerful, declarative framework for creating interactive plots.
    description: >

  -
    name: timevis
    thumbnail: images/daattali-timevis.png
    url: "https://github.com/daattali/timevis#readme"
    jslibs: >
      [vis.js](http://visjs.org/)
    ghuser: daattali
    ghrepo: timevis
    tags: visualization,timeline
    cran: true
    release: stable
    examples: >
      [Demo Shiny app](http://daattali.com/shiny/timevis-demo/)
    ghauthor: daattali
    short: >
      Create interactive timeline visualizations in R.
    description: >
      `timevis` lets you create rich and fully interactive timeline visualizations in R. Timelines can be included in Shiny apps and R markdown documents, or viewed from the R console and RStudio Viewer. `timevis` includes an extensive API to manipulate a timeline after creation, and supports getting data out of the visualization into R. This package is based on the vis.js Timeline module.

